### ISSUE TITLE
USDT & USDC Decimal Places on Blockexplorer

### ISSUE THREAD

**Issue by jwboba** [omgnetwork/optimism#513]
https://blockexplorer.boba.network/tokens shows a total supply of .000000005033 USDT. Decimal is off by ~12 places.

L2 Liquidity Pool shows 5k USDT liquidity.

![image](https://user-images.githubusercontent.com/90710496/134377072-c7890458-09d9-4d8d-b4b3-a98ed241320e.png)

Same thing appears to be happening with USDC.

**Comment by CAPtheorem** [comment]
Ok, this is block explorer specific, token.decimals bug.

**Comment by cby3149** [comment]
Fixed. https://github.com/omgnetwork/blockscout/pull/2

**Comment by jwboba** [comment]
USDC appears to fixed, but USDT is still showing misplaced decimal, unless it takes some time for the fix to show up.

**Comment by cby3149** [comment]
Thanks for reporting the issue. USDT was fixed, too.
